site_name: Data Engineering Essentials
site_url: https://sitename.example
theme:
  name: material
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep orange
      accent: indigo

fonts:
  icon: material/format-font
  preferences:
    - text: Default
    - text: Roboto
      code: Roboto Mono
    - text: OpenDyslexic
      code: OpenDyslexicMono
      src: https://fonts.cdnfonts.com/css/opendyslexic


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/github
      link: https://github.com/Vinicius-Santoro
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/viniciusrio/

copyright: Copyright &copy; 2024 Vinicius Naziozeno Santoro do Rio